# http://docs.codeclimate.com/article/296-engines-available-engines
engines:
  eslint:
    enabled: true
  csslint:
    enabled: true
  nodesecurity:
    enabled: true
ratings:
  paths:
    - "**.js"
exclude_paths:
  - test/**/*
  - api/**/*
  - dist/**/*
  - temp/**/*
  - views/**/*
  - .idea/**/*